### ISSUE TITLE
Best practice - SelemId and Mixer lifetimes

### ISSUE THREAD

**Issue by ashthespy** [diwic/alsa-rs#36]
I'm quite new to rust, and was wondering what the best way to achieve the following is?
As the SelemId is borrowed from the Mixer, there isn't much I can do correct?

```rust
fn get_selem(card: &str, mixer: &str) -> Result<(mixer::Selem), Box<Error>> {
    let selem_id = mixer::SelemId::new(mixer, 0);
    let mixer = mixer::Mixer::new(card, false)?;
    let selem = mixer.find_selem(&selem_id)?;

    Ok((selem))
}
```
```rust
error[E0106]: missing lifetime specifier
  --> playback/src/mixer/alsamixer.rs:12:50
   |
12 | fn get_selem(card: &str, mixer: &str) -> Result<(mixer::Selem), Box<Error>> {
   |                                                  ^^^^^^^^^^^^ expected lifetime parameter
   |
   = help: this function's return type contains a borrowed value, but the signature does not say whether it is borrowed from `card` or `mixer`
```

**Comment by diwic** [comment]
What the code above does:

 1) At Mixer::new, the ALSA library opens `/dev/snd/controlC0` which is a kernel interface to set mixer parameters. (Or `/dev/snd/controlC1` for the second card, etc.) 
 2) When the function ends, the variable of type `Mixer` is dropped, so `/dev/snd/controlC0`  is closed again. 

(It's also a bit confusing since both a local variable, a function parameter and a module are all named `mixer`, but anyhow...)

You can't do anything with the `Selem` when that kernel interface is closed, so the Rust compiler just prevented you from writing such buggy code. The reason `Selem` has a lifetime parameter is because it depends on the `Mixer`, not the `SelemId` or anything else.

The best way to resolve this problem depends on what you want to do (on a higher level than just that specific function) so I can't give more specific advice.

**Comment by ashthespy** [comment]
Thanks for the quick explanation - that makes much more sense now.

What I am attempting to do is get and set the volume, and wanted to avoid rewriting the error chain checking each time when doing this i,e: 
```rust
impl Mixer for AlsaMixer {
    fn open(device: Option<String>) -> AlsaMixer {
        let card = device.unwrap_or(String::from("default"));
        let mixer = String::from("PCM");
        AlsaMixer {
            card: card,
            mixer: mixer,
        }
    }

    fn start(&self) {
    }

    fn stop(&self) {
    }

    fn volume(&self) -> u16 {
        let mixer = alsa::mixer::Mixer::new(&self.card, false).unwrap();
        let selem_id = alsa::mixer::SelemId::new(&self.mixer, 0);
        let selem = mixer.find_selem(&selem_id).unwrap();
        let (min, max) = selem.get_playback_volume_range();
        let volume: i64 = selem.get_playback_volume(alsa::mixer::SelemChannelId::FrontLeft).unwrap();

        let resolution = max - min + 1;
        let multiplier: u16 = (((0xFFFF + 1) / resolution) - 1) as u16;

        volume as u16 * multiplier
    }

    fn set_volume(&self, volume: u16) {
        let mixer = alsa::mixer::Mixer::new(&self.card, false).unwrap();
        let selem_id = alsa::mixer::SelemId::new(&self.mixer, 0);
        let selem = mixer.find_selem(&selem_id).unwrap();
        let (min, max) = selem.get_playback_volume_range();

        let resolution = max - min + 1;
        let factor: u16 = (((0xFFFF + 1) / resolution) - 1) as u16;
        let volume: i64 = (volume / factor) as i64;
        info!("Setting volume: {:?}", volume);
        selem.set_playback_volume_all(volume).unwrap();
    }

    fn get_audio_filter(&self) -> Option<Box<AudioFilter + Send>> {
        None
    }
}
```
Instead I now do something (still not elegant) along these lines:
```rust
impl AlsaMixer {

    fn map_volume(&self, set_volume:Option<u16>) -> Result<(u16),Box<Error>> {
        let mixer  = alsa::mixer::Mixer::new(&self.card, false)?;
        let sid    = alsa::mixer::SelemId::new(&*self.mixer, self.index);

        let selem = mixer.find_selem(&sid).expect("Coundn't find SelemId");
        let (min, max) = selem.get_playback_volume_range();
        let cur_vol = selem.get_playback_volume(alsa::mixer::SelemChannelId::mono()).expect("Couldn't get current volume");
        let range = (max - min) as f64;

        let new_vol:u16;

        if let Some(vol) = set_volume {
            let alsa_volume:i64 = ((vol as f64 / 0xFFFF as f64) * range) as i64 + min;
            debug!("Maping volume {:?} [u16] ->> Alsa {:?} [i64]",vol,alsa_volume);
            selem.set_playback_volume_all(alsa_volume).expect("Couldn't set alsa volume");
            new_vol = vol; // Meh
        } else {
            new_vol =  (((cur_vol - min) as f64 / range) * 0xFFFF as f64) as u16;
            debug!("Maping volume {:?} [u16] <<- Alsa {:?} [i64]",new_vol, cur_vol);
        }


        Ok(new_vol)
    }
}
```
This is part of https://github.com/ashthespy/librespot/blob/alsa/playback/src/mixer/alsamixer.rs

**Comment by diwic** [comment]
Ok, so two solutions:

 1) Let the `AlsaMixer` struct contain a `Mixer` instead of just a String.  The kernel interface will be opened during the entire lifetime of the `AlsaMixer` struct, which is probably good if you're getting/setting the volume repeatedly.

 2) If this is not an option, you can use a closure, something like:

    fn with_selem<F: FnOnce(&mut Selem)>(card: &str, mixer: &str, f: F) {
        let selem_id = mixer::SelemId::new(mixer, 0);
        let mixer = mixer::Mixer::new(card, false)?;
        let mut selem = mixer.find_selem(&selem_id)?;
        f(&mut selem)
    }

**Comment by ashthespy** [comment]
Will explore the closure option - thanks!
