### ISSUE TITLE
EIO on readi in blocking mode

### ISSUE THREAD

**Issue by HEnquist** [diwic/alsa-rs#64]
Thanks for this very nice library! I'm using it in a DSP project and it's working very well.
But now I'm pretty stuck on an issue and need a little help. As far as I understand, when there is no data coming and we are in blocking mode, then readi (https://docs.rs/alsa/0.4.3/alsa/pcm/struct.IO.html#method.readi) should just wait forever or return with one of EBADFD, EPIPE or ESTRPIPE.
My problem is that I get EIO. The specific case I'm struggling with is when capturing from an spdif input on a Raspberry Pi  with a Hifiberry DigiIO, and the source stops the datastream. What happens then is that readi waits for about 3 seconds, then returns with EIO. 
Shoud this be possible? What does it actually mean? 
I would like to handle the situation so that things can just continue when the signal comes back. After starting the spdif stream again I have tried just readi again but that's no good. I also tried prepare(), but that gives EBUSY. Should I try recover()?
One problem here is that I don't have a card that behaves like this myself, so testing many different things is quite slow. Any ideas to narrow down the number of things to try would be highly appreciated!

**Comment by diwic** [comment]
Hi Henrik!

So I cannot answer for whether EIO is something to be occasionally expected from a `readi` call or if it's due to a buggy driver. You might have better luck asking on the alsa-devel mailing list for that.

 >  Should I try recover()

My gut feeling is that it won't help, EIO is too severe. Possibly `drop()` and then start over from `hwparams()` could help, but I'm not sure.

 > One problem here is that I don't have a card that behaves like this myself, so testing many different things is quite slow. Any ideas to narrow down the number of things to try would be highly appreciated!

I think my approach to the problem would be to try with a USB card or similar and just unplug it during the call to `readi`. See what happens. I think you'll get either ENXIO or EIO. Maybe try handling EIO the same way you would handle an unplugged device. That way you can replicate the error at home and come up with a good strategy to handle it.

**Comment by HEnquist** [comment]
Thanks for your answer! I realize now that the error is coming directly from alsa, and there is nothing in alsa-rs that would affect how that part works.
I'll ask the alsa-devel mailing list about the EIO. Good idea about a USB card, I'll try that. 
Cheers,
Henrik
