### ISSUE TITLE
PCM capture to playback and dropouts

### ISSUE THREAD

**Issue by pietervandermeer** [diwic/alsa-rs#94]
I've been using alsa-rs for a while now, and I have to say that it's my favorite audio streaming & MIDI crate by far. It allows me to do almost everything I once did in C with ALSA, but without the all the super verbose error handling.  

I've successfully integrated alsa-rs in my real-time synthesizer engine, and it works like a charm. Superficially, audio capture also works in this engine, but when it starts using more CPU time (>50%), the audio drop outs start. Disable capture and you can push it up to 90%. I'm doing 512 frame latency @ 48 kHz on a PREEMPT kernel, and capturing from the same device as I'm playing on. 

What I'm trying to do here is mixing captured audio directly with synthesized sound. I think for this to work you'd need to fill up your playback stream, forward your capture stream, and then start capturing. I'm linking playback and capture via ```alsa::pcm::link()```. The problem is that forwarding is not supported in alsa-rs.. Is there any way around this?

**Comment by diwic** [comment]
I'm not sure what "forward your capture stream" actually means, could you explain? 

Indeed you should fill up your playback stream before starting playback, then in every buffer fillup loop, see if there is anything in the capture buffer and if so mix it in? Having more than two periods could potentially help here, e g 64 x 4 instead of 128 x 2 samples if your buffer is 512 frames.
